CREATE TABLE species (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name text,
  scientific_name text,
  number_in_wild int, 
  conservation_code text,
  created_at timestamp without time zone DEFAULT now()
  PRIMARY KEY(id)
);

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Northern Goshawk', 'Accipiter gentilis', 50, 'CE');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Black Bear', 'Ursus Americanus', 500, 'T');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Wolverine', 'Gulo gulo', 400, 'CE');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Northern Spotted Owl', 'Strix occidentalis caurina', 200, 'CE');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Gray Wolf', 'Canus grayus', 600, 'T');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Barn Owl', 'T Albas', 60, 'CE');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Common Raven', 'Corvax Corgus', 6000, 'V');

INSERT INTO species(name, scientific_name, number_in_wild, conservation_code) VALUES('Mountain Lion', 'Feline Wildus', 4500, 'V');


CREATE TABLE individuals (
 id INT GENERATED BY DEFAULT AS IDENTITY,
 name text,
 nickname text,
 created_at timestamp without time zone DEFAULT now(),
 species_id int,
 PRIMARY KEY(id),
 FOREIGN KEY (species_id) REFERENCES species(id)
);

INSERT INTO individuals(name, nickname, species_id) VALUES('Goshawk', 'Gossy', 1);

INSERT INTO individuals(name, nickname, species_id) VALUES('Black Bear', 'Tahoe', 2);

INSERT INTO individuals(name, nickname, species_id) VALUES('Wolverine', 'Wally', 2);

INSERT INTO individuals(name, nickname, species_id) VALUES('Gray Wolf', 'Trickster', 2);

INSERT INTO individuals(name, nickname, species_id) VALUES('Common Raven', 'Smartie', 1);

CREATE TABLE sightings (
    id INT GENERATED BY DEFAULT AS IDENTITY,
   date_of_sighting date,
   location varchar(255),
   healty boolean,
    email_of_sighter text,
   individual_id int,
    PRIMARY KEY (id),
    FOREIGN KEY (individual_id) REFERENCES individuals(id)
);

INSERT INTO sightings(date_of_sighting, location, healty, email_of_sighter) VALUES('2021-01-09', 'American River', true, 'user1@gmail.com', 1);